### ISSUE TITLE
MaskedCausalVisionTransformer fails to build — Attention.__init__() got an unexpected keyword argument 'mlp_ratio'

### ISSUE THREAD

**Issue by lorinczszabolcs** [lightly-ai/lightly#2042]
## Bug description

`MaskedCausalVisionTransformer` does not build. This model is the AIM backbone. As a result, the AIM examples, the AIM benchmark, and the [AIM tutorial](https://docs.lightly.ai/self-supervised-learning/examples/aim.html) all fail.

There are two separate faults:

1. `MaskedCausalBlock` sends its block-level arguments (for example `mlp_ratio`) to the `timm` `Attention` layer. `Attention` does not accept them. This gives a `TypeError` for every construction.
2. The AIM examples set `class_token=False` but do not set `global_pool`. `timm` then fails an assertion before it builds the blocks.

## To reproduce

Fault 1: any construction:

```python
from lightly.models.modules import MaskedCausalVisionTransformer

MaskedCausalVisionTransformer(
    img_size=224, patch_size=16, embed_dim=384, depth=12, num_heads=6,
)
```

```
TypeError: Attention.__init__() got an unexpected keyword argument 'mlp_ratio'
```

Fault 2: the AIM example config:

```python
MaskedCausalVisionTransformer(
    img_size=224, patch_size=32, embed_dim=768, depth=12, num_heads=12,
    class_token=False, no_embed_class=True,
)
```

```
AssertionError
```

## Environment

- lightly: `1.5.26` (current release) and `master`.
- timm: all supported versions fail (`timm>=0.9.9`, tested up to `1.0.28`).

## Cause

Fault 1 is a regression from #1841. That PR fixed #1829 (the `proj_bias` error). It forwards all block arguments to `Attention` with `**kwargs`. This also forwards arguments that `Attention` does not accept, for example `mlp_ratio`.

## Suggested fix

Forward only the arguments that `Attention.__init__` accepts. Set `global_pool="avg"` in the AIM examples.

**Comment by gabrielfruet** [comment]
Thank you for filling this! This is really an issue, please feel free to open a PR :)
