### PR TITLE
fix: MaskedCausalVisionTransformer build on all supported timm versions

### LINKED ISSUE #1829: MaskedCausalBlock.__init__() got an unexpected keyword argument 'proj_bias'
Hi,

I am getting the following error when reproducing the [AIM-tutorial](https://docs.lightly.ai/self-supervised-learning/examples/aim.html). Now [timm attention](https://github.com/huggingface/pytorch-image-models/blob/main/timm/models/vision_transformer.py#L67) has 'proj_bias' parameter, which isn't added to the [MaskedCausalBlock init](https://github.com/lightly-ai/lightly/blob/master/lightly/models/modules/masked_causal_vision_transformer.py#L99). Adding this parameter should solve the problem.

timm version: 1.0.14
lightly version: 1.5.19

```
/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:560, in <listcomp>(.0)
    [556](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:556) self.norm_pre = norm_layer(embed_dim) if pre_norm else nn.Identity()
    [558](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:558) dpr = [x.item() for x in torch.linspace(0, drop_path_rate, depth)]  # stochastic depth decay rule
    [559](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:559) self.blocks = nn.Sequential(*[
--> [560](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:560)     block_fn(
    [561](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:561)         dim=embed_dim,
    [562](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:562)         num_heads=num_heads,
    [563](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:563)         mlp_ratio=mlp_ratio,
    [564](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:564)         qkv_bias=qkv_bias,
    [565](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:565)         qk_norm=qk_norm,
    [566](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:566)         proj_bias=proj_bias,
    [567](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:567)         init_values=init_values,
    [568](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:568)         proj_drop=proj_drop_rate,
    [569](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:569)         attn_drop=attn_drop_rate,
    [570](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:570)         drop_path=dpr[i],
    [571](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:571)         norm_layer=norm_layer,
    [572](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:572)         act_layer=act_layer,
    [573](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:573)         mlp_layer=mlp_layer,
    [574](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:574)     )
    [575](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:575)     for i in range(depth)])
    [576](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:576) self.feature_info = [
    [577](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:577)     dict(module=f'blocks.{i}', num_chs=embed_dim, reduction=reduction) for i in range(depth)]
    [578](https://file+.vscode-resource.vscode-cdn.net/c%3A/OSS/AstroCLIP/~/.conda/envs/astroclip/lib/python3.10/site-packages/timm/models/vision_transformer.py:578) self.norm = norm_layer(embed_dim) if final_norm and not use_fc_norm else nn.Identity()

TypeError: MaskedCausalBlock.__init__() got an unexpected keyword argument 'proj_bias'
```

### LINKED ISSUE #2042: MaskedCausalVisionTransformer fails to build — Attention.__init__() got an unexpected keyword argument 'mlp_ratio'
## Bug description

`MaskedCausalVisionTransformer` does not build. This model is the AIM backbone. As a result, the AIM examples, the AIM benchmark, and the [AIM tutorial](https://docs.lightly.ai/self-supervised-learning/examples/aim.html) all fail.

There are two separate faults:

1. `MaskedCausalBlock` sends its block-level arguments (for example `mlp_ratio`) to the `timm` `Attention` layer. `Attention` does not accept them. This gives a `TypeError` for every construction.
2. The AIM examples set `class_token=False` but do not set `global_pool`. `timm` then fails an assertion before it builds the blocks.

## To reproduce

Fault 1: any construction:

```python
from lightly.models.modules import MaskedCausalVisionTransformer

MaskedCausalVisionTransformer(
    img_size=224, patch_size=16, embed_dim=384, depth=12, num_heads=6,
)
```

```
TypeError: Attention.__init__() got an unexpected keyword argument 'mlp_ratio'
```

Fault 2: the AIM example config:

```python
MaskedCausalVisionTransformer(
    img_size=224, patch_size=32, embed_dim=768, depth=12, num_heads=12,
    class_token=False, no_embed_class=True,
)
```

```
AssertionError
```

## Environment

- lightly: `1.5.26` (current release) and `master`.
- timm: all supported versions fail (`timm>=0.9.9`, tested up to `1.0.28`).

## Cause

Fault 1 is a regression from #1841. That PR fixed #1829 (the `proj_bias` error). It forwards all block arguments to `Attention` with `**kwargs`. This also forwards arguments that `Attention` does not accept, for example `mlp_ratio`.

## Suggested fix

Forward only the arguments that `Attention.__init__` accepts. Set `global_pool="avg"` in the AIM examples.

### PR DESCRIPTION
**Pull request by lorinczszabolcs**
Closes #2042.

Two commits:

1. **Forward only attention kwargs in `MaskedCausalBlock`.** The block forwarded all of its block-level kwargs to the `timm` `Attention` layer. `Attention` rejects arguments like `mlp_ratio`, so `MaskedCausalVisionTransformer` failed to build on every supported `timm` version. This is a regression from #1841 (the `**kwargs` forwarding that fixed #1829). The fix selects the kwargs from `Attention.__init__`'s signature, so it keeps #1841's version-robustness without a hardcoded argument list. Adds a regression test for the block and the model, this backbone had none before.

2. **Set `global_pool="avg"` in the AIM examples and benchmark.** The examples build the backbone with `class_token=False` but no `global_pool`, which trips `timm`'s `class_token or global_pool != "token"` assertion at init, before the block bug is even reached. AIM's self-supervised path uses `forward_features`, so `"avg"` satisfies the assertion without changing behavior. Regenerated the notebooks.

Verified on `timm` `0.9.9`, `1.0.14`, and `1.0.28`. `make format-check` passes and the notebooks are up to date.

### CODE REVIEW

**Comment by lorinczszabolcs** [comment]
Addressed the failing tests.

File: lightly/models/modules/masked_causal_vision_transformer.py [hunk 1]
```diff
@@ -120,9 +121,16 @@ class for input parameters.
             *args,
             **kwargs,
         )
+        # Keep only the kwargs that timm's Attention accepts. Block-level kwargs
+        # such as mlp_ratio do not apply to the attention layer.
+        attention_kwargs = {
+            key: value
+            for key, value in kwargs.items()
```
Comment (gabrielfruet) [inline lightly/models/modules/masked_causal_vision_transformer.py:128]: This wouldn't work for 

`scale_attn_norm=True`

It's fine for me since we don't use it, lets keep it that way.

**Review by gabrielfruet — APPROVED** [review]
